name: MinecraftPlugin
version: 0.9
author: Adrien13720
main: fr.adrien13720.minecraftplugin.Main
api-version: 1.17
commands:
  test:
    description: Commande de test
    permission: test.use
  alert:
    description: Commande de broadcast
    permission: bc.use
  info:
    description: Commande info
    permission: info.use
  setleaderboard:
    description: Commande pour set les leaderboards
    permission: setleaderboard.use
  faction:
    description: Regroupe les commandes de faction
  spawn:
    description: Commande pour se tp au spawn