name: MinecraftPlugin
version: 0.0.1
author: Adrien13720
main: fr.adrien13720.minecraftplugin.Main
api-version: 1.17
commands:
  test:
    description: Ceci est une commande de test
    permission: test.use
  alert:
    description: Ceci est une commande d'alerte
    permission: bc.use
  info:
    description: Ceci est une commande pour récup les leaderboards
    permission: info.use
  setleaderboard:
    description: Commande à utiliser pour changer manuellement les scoreboards
    permission: set.use
  spawn:
    description: Ceci est une commande pour se tp au spawn
  faction:
    description: Ceci est une commande
   